In [1]:

import pandas as pd
import numpy as np

In [2]:
#Load Data

df = pd.read_csv(r'C:\Users\dell\Desktop\New dashboard , combine companies\dataset\Agmo\AGMO NO Pass new\CSV file\before automated clean data_combine_all.CSV')

In [4]:
# Save the updated DataFrame as a CSV file
df.to_csv(r'C:\Users\dell\Desktop\New dashboard , combine companies\dataset\Agmo\AGMO NO Pass new\automated data clean\before automated clean data.csv', index=False)

In [5]:
#Started data cleaning

## Add a new column to the DataFrame
df['Shareholder TYPES(new sort)'] = ''

# Iterate over the rows in the DataFrame and update the new column based on the Investor_Type column
for index, row in df.iterrows():
    investor_type = row['Investor_Type']
    if investor_type in ["RETAIL BODY CORPORATES - PRIVATE LIMITED COMPANY", "CORPORATE BODY - BANK/FINANCE COMPANY", "RETAIL BODY CORPORATES - PRIVATE LIMITED COMPANY", "CORPORATE BODY - CO-OPERATIVES"]:
        df.at[index, 'Shareholder TYPES(new sort)'] = 'CORPORATE'
    elif investor_type == "RETAIL BODY CORPORATES - LIMITED COMPANY":
        df.at[index, 'Shareholder TYPES(new sort)'] = 'CORPORATE'
    elif investor_type in ["INSTITUTIONAL BODY CORPORATES - LIMITED COMPANY", "CORPORATE BODY - INVESTMENT TRUST/FOUNDATION", "OTHERS"]:
        df.at[index, 'Shareholder TYPES(new sort)'] = 'INSTITUTIONAL'
    else:
        df.at[index, 'Shareholder TYPES(new sort)'] = 'INDIVIDUAL'

# Print the updated DataFrame to confirm the new column was added and updated

,No,Company,Member_No,Investor_ID,P_Code,P_Branch,P_Name,CDS,Holder_Name,Address_1,...,State,Country,Nation,Race,Investor_Type,Beneficiary,Qualifier,Date,Shareholding,Shareholder TYPES(new sort)
0,1,Agmo Holdings Berhad,72054331,820615-14-5876,12,1,MALACCA SECURITIES SDN BHD,72054331,AAINA BINTI MOHD YUSAK,NO 7 JALAN TK5/26,...,SELANGOR,MALAYSIA,MALAYSIAN,BUMIPUTRA,INDIVIDUAL,NaN,NaN,2023-03-02 00:00:00+00:00,13000,INDIVIDUAL
1,2,Agmo Holdings Berhad,50747054,630521-01-5475,66,1,HONG LEONG INVESTMENT BANK BERHAD,50747054,AB MALEK BIN MOHAMED,30-1 JLN LIM POON,...,JOHOR,MALAYSIA,MALAYSIAN,BUMIPUTRA,INDIVIDUAL,NaN,NaN,2023-03-02 00:00:00+00:00,18000,INDIVIDUAL
2,3,Agmo Holdings Berhad,44616639,730809-10-5961,73,1,KENANGA INVESTMENT BANK BERHAD,44616639,ABD RAHIM BIN AHMAD,LOT 3745 BATU 7,...,SELANGOR,MALAYSIA,MALAYSIAN,BUMIPUTRA,INDIVIDUAL,NaN,NaN,2023-03-02 00:00:00+00:00,4000,INDIVIDUAL
3,4,Agmo Holdings Berhad,66593005,900924-14-6813,12,1,MALACCA SECURITIES SDN BHD,66593005,ABDUL HALIM BIN NASRUL,NO 20 BLOCK Y KG SRI WIRA DAMAI,...,SELANGOR,MALAYSIA,MALAYSIAN,BUMIPUTRA,INDIVIDUAL,NaN,NaN,2023-03-02 00:00:00+00:00,2700,INDIVIDUAL
4,5,Agmo Holdings Berhad,74213430,600212-08-5771,12,1,MALACCA SECURITIES SDN BHD,74213430,ABDUL MALEK BIN HARUN,NO 36,...,SELANGOR,MALAYSIA,MALAYSIAN,BUMIPUTRA,INDIVIDUAL,NaN,NaN,2023-03-02 00:00:00+00:00,3000,INDIVIDUAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14983,3689,Agmo Holdings Berhad,2474914,460310-10-5324,86,1,AMINVESTMENT BANK BERHAD,2474914,ZAINI BINTI ISMAIL,NO 31 JALAN AMINUDDIN BAKI,...,W. PERSEKUTUAN,MALAYSIA,MALAYSIAN,BUMIPUTRA,INDIVIDUAL,NaN,NaN,2022-11-29 16:00:00+00:00,30000,INDIVIDUAL
14984,3690,Agmo Holdings Berhad,70703681,631009-04-5207,98,1,MAYBANK INVESTMENT BANK BERHAD,70703681,ZAM ARIFFIN BIN ISMAIL,NO 40 JALAN SUARASA 4/2,...,SELANGOR,MALAYSIA,MALAYSIAN,BUMIPUTRA,INDIVIDUAL,NaN,NaN,2022-11-29 16:00:00+00:00,140000,INDIVIDUAL
14985,3691,Agmo Holdings Berhad,26056044,670329-10-6349,68,19,AFFIN HWANG INVESTMENT BANK BERHAD,26056044,ZANIOL @ ZAINOL BIN MADROP,21 JALAN TUN TEJA 35/4B,...,SELANGOR,MALAYSIA,MALAYSIAN,BUMIPUTRA,INDIVIDUAL,NaN,NaN,2022-11-29 16:00:00+00:00,20000,INDIVIDUAL
14986,3692,Agmo Holdings Berhad,65275828,630202-07-5323,98,2,MAYBANK INVESTMENT BANK BERHAD,65275828,ZARIR BIN ABU BAKAR,NO 107 LORONG BLM 3/22,...,KEDAH,MALAYSIA,MALAYSIAN,BUMIPUTRA,INDIVIDUAL,NaN,NaN,2022-11-29 16:00:00+00:00,2000,INDIVIDUAL
14987,3693,Agmo Holdings Berhad,44071660,791210-14-5974,68,19,AFFIN HWANG INVESTMENT BANK BERHAD,44071660,ZIRWATUL HANA BINTI PISON,"NO 74, JALAN CERI 6/3,",...,SELANGOR,MALAYSIA,MALAYSIAN,BUMIPUTRA,INDIVIDUAL,NaN,NaN,2022-11-29 16:00:00+00:00,5500,INDIVIDUAL

In [6]:
# Add new columns to the DataFrame
df['Pledge(Broker)'] = ''
df['Pledge(Shareholder)'] = ''

# Iterate over the rows in the DataFrame and update the new columns based on the Qualifier column
for index, row in df.iterrows():
    qualifier = row['Qualifier']
    if isinstance(qualifier, float) and np.isnan(qualifier):
        continue
    pledge_parts = str(qualifier).split('FOR')
    if len(pledge_parts) == 2:
        df.at[index, 'Pledge(Broker)'] = pledge_parts[0].strip()
        df.at[index, 'Pledge(Shareholder)'] = pledge_parts[1].strip()
    else:
        df.at[index, 'Pledge(Broker)'] = pledge_parts[0].strip()

In [8]:
#copy 'Pledge(Shareholder)' in to 'Combine Name (CDS + NOMINEE)
df['Combine Name (CDS + NOMINEE)'] = df['Pledge(Shareholder)']

In [10]:
# Copy data from Qualifier column to 'Combine Name (CDS + NOMINEE) column for empty cells only
df['Combine Name (CDS + NOMINEE)'] = df['Combine Name (CDS + NOMINEE)'].replace('', pd.NA).fillna(df['Qualifier'])

In [11]:
# Save the updated DataFrame as a CSV file
df.to_csv(r'C:\Users\dell\Desktop\New dashboard , combine companies\dataset\Agmo\AGMO NO Pass new\automated data clean\untransfer automated clean data.csv', index=False)

In [12]:
# Copy data from Holder_Name column to 'Combine Name (CDS + NOMINEE) column for empty cells only
df['Combine Name (CDS + NOMINEE)'] = df['Combine Name (CDS + NOMINEE)'].replace('', pd.NA).fillna(df['Holder_Name'])

In [14]:
# Update the Pledge(Shareholder) column
df['Pledge(Shareholder)'] = df['Pledge(Shareholder)'].str.replace(r'\(.*', '', regex=True)

In [15]:
#do gender colunn
for index, row in df.iterrows():
    investor_type = row['Investor_Type']
    investor_id = row['Investor_ID']
    if investor_type == 'INDIVIDUAL':
        if investor_id[-1].isnumeric():
            last_digit = int(investor_id[-1])
            if last_digit % 2 == 0:
                df.at[index, 'Gender'] = 'FEMALE'
            else:
                df.at[index, 'Gender'] = 'MALE'
        else:
            continue

In [16]:
# do age column 
df['Age'] = ''

# Iterate over the rows in the DataFrame and update the new column based on the Investor_ID column
for index, row in df.iterrows():
    investor_type = row['Investor_Type']
    investor_id = row['Investor_ID']
    if investor_type == 'INDIVIDUAL':
        if investor_id[:2].isdigit():
            first_two_digits = int(investor_id[:2])
            if 20 <= first_two_digits <= 99:
                df.at[index, 'Age'] = 2023 - (1900 + first_two_digits)
            elif 0 <= first_two_digits <= 20:
                df.at[index, 'Age'] = 2023 - (2000 + first_two_digits)
            else:
                continue
        else:
            continue

In [17]:
df['Combine Name (CDS + NOMINEE)'] = df['Combine Name (CDS + NOMINEE)'].str.replace(r'\(.*\)', '', regex=True)

In [18]:
# Save the updated DataFrame as a CSV file
df.to_csv(r'C:\Users\dell\Desktop\New dashboard , combine companies\dataset\Agmo\AGMO NO Pass new\automated data clean\before do IVT.csv', index=False)

In [19]:

# Replace IVT with data from Holder_Name and Pledge(Broker) in Combine Name (CDS + NOMINEE) column
for index, row in df.iterrows():
    if 'IVT' in row['Combine Name (CDS + NOMINEE)']:
        holder_name = row['Holder_Name']
        pledge_broker = row['Pledge(Broker)']
        new_name = holder_name + ' (' + pledge_broker + ')'
        df.at[index, 'Combine Name (CDS + NOMINEE)'] = new_name

In [22]:
df['Overall Row'] = range(1, len(df) + 1)

In [24]:
# Save the updated DataFrame as a CSV file
df.to_csv(r'C:\Users\dell\Desktop\New dashboard , combine companies\dataset\Agmo\AGMO NO Pass new\automated data clean\automated clean data.csv', index=False)